export const REGIONES= {
    'Metropolitana': [
        'Peñalolén',
        'San Joaquín',
        'Puente Alto',
        'Ñuñoa',
        'La Reina',
        'La Florida',
        'Lo Espejo',
        'Cerrillos',
        'Cerro Navia',
        'Conchalí',
        'El Bosque',
        'Estación Central',
        'Huechuraba',
        'Independencia',
        'La Cisterna',
        'San Miguel',
    ],
    'Araucanía': [
        'Temuco',
        'Padre Las Casas',
        'Villarrica',
        'Pucón',
        'Angol',
        'Lautaro',
        'Freire',
        'Pitrufquén',
    ],
    'Ñuble': [
        'Chillán',
        'Chillán Viejo',
        'San Carlos',
        'Bulnes',
        'Quirihue',
        'Coelemu',
        'Pemuco',
        'Yungay',
    ],
};